apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kimai.fullname" . }}-secret
  labels:
    {{- include "kimai.labels" . | nindent 4 }}
data:
  ADMINMAIL: {{ .Values.kimai.adminMail | b64enc }}
  ADMINPASS: {{ .Values.kimai.adminPass | b64enc }}
  TRUSTED_HOSTS: {{ printf "%s,%s" "localhost" .Values.ingress.hostname | b64enc }}
  {{- if .Values.externalDatabase.enabled }}
  DATABASE_URL: {{ printf "mysql://%s:%s@%s/%s" .Values.externalDatabase.user .Values.externalDatabase.pass .Values.externalDatabase.host .Values.externalDatabase.database | b64enc }}
  {{- else }}
  DATABASE_URL: {{ printf "mysql://%s:%s@%s/%s" .Values.mysql.auth.username .Values.mysql.auth.password .Values.mysql.fullnameOverride .Values.mysql.auth.database | b64enc }}
  {{- end }}
