apiVersion: v2
name: rundeck-exporter
description: Rundeck Metrics Exporter for Prometheus.
# Definindo os metadados do Chart

# Defina o nome do Chart, descrição e versão

type: application

version: 0.1.0

appVersion: "1.16.0"
keywords:
  - rundeck-exporter

maintainers:
  - name: Natália Granato
    email: natalia.granato@jackexperts.com
