apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-zabbix-ui
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
data:
  ZBX_SERVER_HOST: {{ .Values.zabbixweb.ZBX_SERVER_HOST | b64enc}}
  ZBX_SERVER_PORT: {{ .Values.zabbixweb.ZBX_SERVER_PORT | b64enc}}
  DB_SERVER_HOST: {{ .Values.zabbixweb.DB_SERVER_HOST | b64enc}}
  DB_SERVER_PORT: {{ .Values.zabbixweb.DB_SERVER_PORT | b64enc}}
  POSTGRES_USER: {{ .Values.zabbixweb.POSTGRES_USER | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.zabbixweb.POSTGRES_PASSWORD | b64enc}}
  POSTGRES_DB: {{ .Values.zabbixweb.POSTGRES_DB | b64enc}}
