apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-zabbix-server
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
data:
  DB_SERVER_HOST: {{ .Values.zabbixServer.DB_SERVER_HOST | b64enc}}
  POSTGRES_USER: {{ .Values.zabbixServer.POSTGRES_USER | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.zabbixServer.POSTGRES_PASSWORD | b64enc}}
  POSTGRES_DB: {{ .Values.zabbixServer.POSTGRES_DB | b64enc}}
